import Head from 'next/head'
import App from '../components/App.js';
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to YourSpace
        </h1>
        <p>
          An earth citizens website to access pictures from NASA's Astronomy Picture of the Day and
          Mars Rover Photos APIs provided for free on the internet.
        </p>
        <App></App>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://api.nasa.gov/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by api.nasa.gov
        </a>
      </footer>
    </div>
  )
}
